version: '3.4'

x-ffmoeg:
  &ffmpeg
  image: jrottenberg/ffmpeg:3.4
  restart: always
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
  network_mode: host
  cap_add:
    - ALL

services:
  telesur-hd:
    << : *ffmpeg
    command: >
      -i udp://225.1.1.8:3000
      -g ${GOP-15} -f flv
      -c:v h264_nvenc -preset:v ${PRESET-llhq} -profile:v ${PROFILE-high}
      -c:a libfdk_aac -vbsf h264_mp4toannexb -strict experimental
      rtmp://admin:Webteles2@wsedvr.openmultimedia.biz:1935/live/espanol.stream

  telesur-en:
    << : *ffmpeg
    command: >
      -i udp://225.1.1.2:3000 -map i:0x411 -map i:0x412
      -g ${GOP-15} -f flv
      -c:v h264_nvenc -preset:v ${PRESET-llhq} -profile:v ${PROFILE-high}
      -c:a libfdk_aac -vbsf h264_mp4toannexb -strict experimental
      rtmp://admin:Webteles2@wsedvr.openmultimedia.biz:1935/live/english.stream
